name: "Jest Annotations & Coverage for testing before PR"
description: "Jest action adding checks and annotations to your pull requests and comment them with code coverage results."
branding:
  icon: "check"
  color: "blue"
inputs:
  test-command:
    description: "The test command to run"
    required: false
    default: "npm test"
  working-directory:
    description: "Subdirectory to run tests in"
    required: false
    default: ""
  coverage-comment:
    description: "Comment PRs with code coverage"
    required: false
    default: "true"
  with-detail:
      description: "Comment PRs with detail summary"
      required: false
      default: "false"
  changes-only:
    description: "Only run tests on changed files (over base branch)"
    required: false
    default: "false"
  check-name:
    description: "Status check name"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
